version: '2'
services:
    pkedziennik-app:
        image: pkedziennik
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pkedziennik-postgresql:5432/pkedziennik
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pkedziennik-postgresql:
        extends:
            file: postgresql.yml
            service: pkedziennik-postgresql
